# Generated by Django 3.1.2 on 2020-11-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitapp',
            name='root',
            field=models.FilePathField(default='/home/keyvan/sites/keyvank/keyvank.github.io'),
            preserve_default=False,
        ),
    ]
