# Generated by Django 3.1.2 on 2020-11-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_gitapp_root'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitapp',
            name='root',
            field=models.FileField(upload_to=''),
        ),
    ]
