# Generated by Django 3.1.2 on 2020-11-03 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_gitapp_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gitapp',
            name='port',
        ),
    ]
